CONTRIBUTORS
_content/tour/static/partials/list.html
_content/tour/variables.article
_content/tour/welcome.article

Fixed phrasing in variable article

---

CONTRIBUTORS
_content/tour/struct-types/example4.go

The existing URL does not work...

upd url to struct layout tool

---

CONTRIBUTORS
_content/tour/goroutines.article

I assume this is a typo and it should be "you" instead of "Iyou".

fix: typo Iyou

---

_content/tour/error-handling.article

https://github.com/ardanlabs/gotour/issues/32

Update extra reading links in "errors"

---

CONTRIBUTORS
_content/tour/algorithms-searches.article
_content/tour/algorithms/data/hash_map.go
_content/tour/algorithms/data/tree_binary.go
_content/tour/algorithms/fun/freq_concurrent.go
_content/tour/algorithms/searches/binary_iterative.go
_content/tour/algorithms/sorting/insertion.go
_content/tour/arrays.article
_content/tour/context.article
_content/tour/generics-struct-types.article
_content/tour/generics-type-constraints.article
_content/tour/generics/behavior-constraints/example3.go
_content/tour/generics/slice-constraints/example1.go
_content/tour/generics/type-constraints/answer1.go
_content/tour/generics/type-constraints/example1.go
_content/tour/generics/type-constraints/exercise1.go
_content/tour/interfaces.article
_content/tour/pointers.article
_content/tour/pointers/example4.go
_content/tour/welcome.article

Hello Ardan Labs team, It's a great project! I found some typos in the content and the code examples here are the fixes.

Fix typos in some content and examples

---

_content/tour/functions.article

Previous sections in the "Ultimate Go Tour" had more thorough explanations. This PR adds an explanation for the function section. Modify this to your liking. 😃

augments func explanation

---

CONTRIBUTORS

The instructions didn't specify if the list should be sorted by first or last name, and the list was out of order in both regards, so I added myself to the list, then sorted the list by first name.

adds Todd McLeod as a contributor - he has signed the CLA

---

_content/tour/per/constants.article
_content/tour/per/maps.article

translated constants

---

_content/tour/spa/algorithms-numbers.article
_content/tour/spa/algorithms-searches.article

The word 'array' can stay as array cause it is very common to use it as such in spanish contexts as well. Translating to arreglo would be more confusing..
Happy reviewing.

[Translation] [Spanish]: Translated algorithms-numbers and algorithms-searches articles 

---

_content/tour/ind/algorithms-bits-seven.article
_content/tour/ind/variables.article

- translate variables.article to bahasa indonesia
- correct small miss translation from  https://github.com/ardanlabs/gotour/pull/63

[Translation] [Bahasa Indonesia]: variable article

---

_content/tour/por/embedding.article
_content/tour/por/exporting.article
_content/tour/por/generics-struct-types.article

Translating the following files:
- embedding.article
- exporting.article
- generics-struct-types.article

Portuguese brazil

---

_content/tour/rus/_en_ru_dictionary.yml

Add a small en-ru dictionary with frequently used technical terms

[Translation] [russian] - Adds en_ru dictionary with frequently used tech terms

---

_content/tour/spa/algorithms-bits-seven.article
_content/tour/spa/algorithms-data.article

Hey! As my first contribution here I started translating those two articles. If you have any comments or sugestions for future work just let me know.

[Translation] [Spanish] Bits and data articles

---

_content/tour/por/algorithms-data.article

Translation of file algorithms-data.article to brazilian portuguese.

[Translation] [Portuguese Brazil]: algorithms-data

---

_content/tour/por/algorithms-bits-seven.article

Translation of algorithms-bits-seven article to pt-BR.

[Translation] [Portuguese Brazil]: algorithms-bits-seven article

---

_content/tour/por/algorithms-numbers.article

Translation of algorithms-numbers article to pt-BR.

[Translation] [Portuguese Brazil]: algorithms-numbers article

---

_content/tour/por/context.article

Translation of context article to pt-BR.

[Translation] [Portuguese Brazil]: context article

---

_content/tour/por/interfaces.article

Translation of interfaces article to pt-BR.

[Translation] [Portuguese Brazil]: interfaces article

---

_content/tour/por/methods.article

Translation of methods.article to pt-BR.

[Translation] [Portuguese Brazil]: methods article

---

_content/tour/por/algorithms-searches.article
_content/tour/por/channels.article
_content/tour/por/generics-behavior-constraints.article
_content/tour/por/generics-underlying-types.article
_content/tour/por/slices.article

This PR includes the following files:
- slices.article
- generics-underlying-types.article
- generics-struct-types.article

[Translation] [Portuguese Brazil]

---

_content/tour/por/static/js/values.js
_content/tour/por/static/partials/list.html
_content/tour/por/template/index.tmpl

Tranlation of the index page to pt-BR.

[Translation] [Portuguese Brazil]: index page

---

_content/tour/por/functions.article

Translation of functions article to pt-BR.

[Translation] [Portuguese Brazil]: functions

---

_content/tour/por/pointers.article

Translation of pointers article to pt-BR.

[Translation] [Portuguese Brazil]: pointers

---

_content/tour/spa/generics-channels.article

WIP: [translation][spanish]: Translated some common content + Welcome article

[Translation] [spanish] `generics-channels` article

---

_content/tour/por/composition-grouping.article
_content/tour/por/error-handling.article
_content/tour/por/goroutines.article

composition-grouping.article - translation
error-handling.article - translation
goroutines.article - translation

[Translation] [Portuguese Brazil]:

---

_content/tour/ita/algorithms-slices.article
_content/tour/ita/algorithms-sorting.article
_content/tour/ita/algorithms-strings.article
_content/tour/ita/arrays.article
_content/tour/ita/channels.article

[Translation] [Italian] first batch of five

---

_content/tour/por/algorithms-slices.article
_content/tour/por/composition-decoupling.article
_content/tour/por/generics-slice-constraints.article

translation of the following files:
- generics-slice-constraints.article 
- algorithms-slices.article 
- composition-decoupling.article

[Translation][Portuguese Brazil] generics-slice-constraints.article algorithms-slices.article composition-decoupling.article

---

_content/tour/swa/arrays.article
_content/tour/swa/channels.article

- Translated Channels.article from English to Swahili

[Translation] [Swahili] : channels.article

---

_content/tour/swa/arrays.article

- Translates  the Arrays article from English to Swahili

[Translation][Swahili]:arrays.article

---

_content/tour/swa/composition-assertions.article

- Translated composition-assertions article from Eng to Swahili

[Translation] [Swahili] : composition-assertions.article

---

_content/tour/spa/algorithms-fun.article
_content/tour/spa/algorithms-slices.article
_content/tour/spa/algorithms-sorting.article

- Fun article
- Slices article
- Algorithm sorting

[translation][spanish]: translation of more articles

---

_content/tour/por/composition-decoupling.article
_content/tour/por/composition-pollution.article
_content/tour/por/data_race.article
_content/tour/por/generics-channels.article
_content/tour/por/generics-hash-table.article

composition-pollution.article
generics-channels.article
composition-pollution.article
data_race.article

[Translation] [Portuguese Brazil]: composition-pollution.article generics-channels.article composition-pollution.article data_race.article

---

_content/tour/por/static/partials/editor.html
_content/tour/por/welcome.article

Buttons translation. I didn't translate Run to Executar because the UI cuts it, there is space only for a short word.

[Translation] [Portuguese Brazil]: buttons

---

_content/tour/ind/algorithms-searches.article

Bahasa Indonesia translation for algorithms-searches

 [Translation] [Bahasa Indonesia]: algorithms-searches article

---

_content/tour/ita/composition-assertions.article
_content/tour/ita/composition-decoupling.article
_content/tour/ita/composition-grouping.article
_content/tour/ita/composition-mocking.article
_content/tour/ita/composition-pollution.article

[Translation] [Italian] second batch of five

---

_content/tour/ind/pointers.article

Bahasa Indonesia translation for article pointer

[Translation] [Bahasa Indonesia]: pointer article

---

_content/tour/pol/algorithms-bits-seven.article

Fix polish translation for bits

---

_content/tour/vie/algorithms-bits-seven.article
_content/tour/vie/algorithms-data.article
_content/tour/vie/algorithms-fun.article
_content/tour/vie/algorithms-numbers.article
_content/tour/vie/algorithms-searches.article
_content/tour/vie/algorithms-slices.article
_content/tour/vie/algorithms-sorting.article
_content/tour/vie/algorithms-strings.article
_content/tour/vie/algorithms/fun/barber.go
_content/tour/vie/template/index.tmpl
_content/tour/vie/welcome.article

Translate to Vietnamese: Algorithms and Welcome

Vietnamese Algorithms and Welcome

---

_content/tour/ita/algorithms-slices.article
_content/tour/ita/arrays.article
_content/tour/ita/static/js/values.js

welcome page fixes

---

_content/tour/ita/welcome.article

italian fixes welcome page

---

_content/tour/ind/algorithms-slices.article

bahasa indonesia transaltion for algorithm-slices.article

 [Translation] [Bahasa Indonesia]: algorithms-slices article

---

_content/tour/ind/functions.article

bahasa indonesia translation for functions.article

 [Translation] [Bahasa Indonesia]: function article

---

_content/tour/vie/channels.article

[Translation] [Vietnamese] Channels

---

_content/tour/vie/functions.article

Translate function to Vietnamese

Translate function to Vietnamese

---

_content/tour/swa/composition-decoupling.article

-  Translates composition decoupling article from English to swahili

  [Translation] [Swahili]: Composition decoupling article

---

_content/tour/rus/algorithms-bits-seven.article
_content/tour/rus/algorithms-data.article
_content/tour/rus/algorithms-strings.article

Initial work on Algorithms section

[Translation] [russian] - translates algorithms into Russian

---

_content/tour/rus/_en_ru_dictionary.yml

[Translation] [russian] dictionary update 

---

_content/tour/rus/welcome.article

[Translation] [russian] welcome.article

---

_content/tour/ind/algorithms-data.article

bahasa indonesia translation for algorithms-data.article

 [Translation] [Bahasa Indonesia]: algorithms-data.article

---

_content/tour/ind/generics-underlying-types.article

bahasa indonesia translation for generics-underlying-types.article

 [Translation] [Bahasa Indonesia]: generics-underlying-types.article

---

_content/tour/ind/generics-hash-table.article

bahasa indonesia translation for generics-hash-table.article

 [Translation] [Bahasa Indonesia]: generics-hash-table.article

---

_content/tour/ind/error-handling.article

bahasa indonesia translation for error-handling.article

 [Translation] [Bahasa Indonesia]: error-handling.article

---

_content/tour/ind/generics-type-constraints.article

bahasa indonesia translation for generics-type-constraints.article

[Translation] [Bahasa Indonesia]: generics-type-constraints.article

---

_content/tour/ind/generics-slice-constraints.article

bahasa indonesia translation for generisc-slice-constraints article

[Translation] [Bahasa Indonesia]: generisc-slice-constraints article

---

_content/tour/ind/exporting.article

bahasa indonesia translation for exporting.article

 [Translation] [Bahasa Indonesia]: exporting.article

---

_content/tour/ind/composition-decoupling.article

bahasa indonesia translation for composition-decoupling article

 [Translation] [Bahasa Indonesia]: composition-decoupling

---

_content/tour/ind/data_race.article

bahasa indonesia translation for data_race.article

 [Translation] [Bahasa Indonesia]: data_race.article

---

_content/tour/ind/welcome.article

Bahasa Indonesia translation for welcome article

 [Translation] [Bahasa Indonesia]: welcome article

---

_content/tour/ind/embedding.article

bahasa indonesia translation for embedding.article

 [Translation] [Bahasa Indonesia]: embedding.article

---

_content/tour/spa/algorithms-strings.article

Hello 👋🏽 
Here are the translations for the string operations page.
I will continue with the arrays page now.
Please let me know if I need to adjust anything.

[translations][spanish] String Operations Page

---

_content/tour/vie/struct-types.article

Translate Struct type to Vietnamese

Translate struct to Vietnamese

---

_content/tour/vie/composition-assertions.article

Translate assertions into vietnamese

Vietnamese assertions

---

_content/tour/ind/arrays.article

bahasa indonesia translation for arrays.article file

[Translation] [Bahasa Indonesia]: arrays article

---

_content/tour/ind/channels.article

Bahasa Indonesia Translation for channels.article

 [Translation] [Bahasa Indonesia]: channels.article

---

_content/tour/ind/composition-mocking.article

bahasa indonesia transalation for composition-mocking.article

[Translation] [Bahasa Indonesia]: composition-mocking

---

_content/tour/ind/goroutines.article

bahasa indonesia translation for goroutines.article

[Translation] [Bahasa Indonesia]: goroutines article

---

_content/tour/ind/generics-basics.article

bahasa indonesia translation for generics-basics.article

[Translation] [Bahasa Indonesia]: generics-basic article

---

_content/tour/ind/composition-assertions.article

bahasa indonesia translation for composition-aseertions.article

 [Translation] [Bahasa Indonesia]: composition-assertions article

---

_content/tour/ind/generics-behavior-constraints.article

bahasa indonesia translation for generics-behavior-constraints article

 [Translation] [Bahasa Indonesia]:  generics-behavior-constraints article

---

_content/tour/ind/composition-pollution.article

bahasa indonesia translation for composition-pollution.article

 [Translation] [Bahasa Indonesia]: composition-pollution.article

---

_content/tour/ind/methods.article

bahasa indonesia translation for methods.article

[Translation] [Bahasa Indonesia]: methods.article

---

_content/tour/ind/maps.article

bahasa indonesia translation for maps.article

 [Translation] [Bahasa Indonesia]: maps article

---

_content/tour/ind/interfaces.article

bahasa indonesia translation for interfaces.article

[Translation] [Bahasa Indonesia]: interfaces.article

---

_content/tour/ind/generics-multi-type-params.article

bahasa indonesia translation for generics-multi-type-params article

[Translation] [Bahasa Indonesia]: generics-multi-type-params.article

---

_content/tour/ind/generics-struct-types.article

bahasa indonesia translation for generisc-struct-types.article

 [Translation] [Bahasa Indonesia]: generisc-struct-types.article

---

_content/tour/ind/generics-channels.article

bahasa indonesia translation for generics-channels.article

 [Translation] [Bahasa Indonesia]: generics-channels.article

---

_content/tour/ind/context.article

bahasa indonesia translation for context.article

 [Translation] [Bahasa Indonesia]: context.article

---

_content/tour/ind/algorithms-sorting.article

bahasa indonesia translation for algorithms-sorting.article

 [Translation] [Bahasa Indonesia]: algorithms-sorting article

---

_content/tour/ind/algorithms-strings.article

bahasa indonesia translation for algoritms-string.article

[Translation] [Bahasa Indonesia]: algorithms-string article

---

_content/tour/ind/composition-grouping.article

bahasa indonesia translation for composition-grouping.article

 [Translation] [Bahasa Indonesia]: composition-grouping.article

---

_content/tour/vie/generics-basics.article

Translate Generic - Basics into Vietnamese

Vietnamese -  Generic Basics

---

_content/tour/vie/generics-behavior-constraints.article

Translate to Vietnamese: Generic Behavior Constraints article

Translate to Vietnamese: Generic Behavior Constraints
